### ISSUE TITLE
PA Review:User Auth

### ISSUE THREAD

**Issue by uroshima** [uroshima/Football-Talk#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
   - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
   - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
   - [x] Going to a random route `/#/helloworld` should redirect to either `/`, `/login`, or `/signup`
   - [x] Errors should display for both `/signup` and `/login`
- [x] Adequate and appropriate seeds
   - [x] Demo Login Works

* My errors are not showing immediately but only when you try to login/signup again after you fail once..I need to fix that

**Comment by rkoron007** [comment]
- check out the difference in styling between your modal and their modal. Look carefully at the font differences and try to style closely to their general style. The modal backdrop could also be the same color. Don't be afraid to use a color picker and grab their colors directly!

![screen shot 2018-08-15 at 3 32 24 pm](https://user-images.githubusercontent.com/32436232/44176882-77356680-a0a0-11e8-88ab-f1c8d9dd419f.png)

- Errors pop up but only after the modal has closed. Make sure the modal is kept in place so the user is able to see the errors.

![screen shot 2018-08-15 at 3 39 31 pm](https://user-images.githubusercontent.com/32436232/44177153-76e99b00-a0a1-11e8-99b9-b654d99e7118.png)


- Make sure to redirect anytime I try to go to a random route

- You are doing great dude, just keep it going :)

**Comment by uroshima** [comment]
For the styling part, I really wanted to use that photo in my modal..but because of the grey/blackish background I didn't add any text because with text it looks prety bad..so I decided to keep it simple and show only the inputs..Maybe I should reorganize them to look a little nicer atleast. 
I fix the redirecting (it's redirecting to the homepage now) and I'll try to fix the errors tonight
Thanks Rose
